-- Drop table employees if exists
DROP TABLE IF EXISTS employees;

-- Create table employees
CREATE TABLE employees (
 id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name        varchar(40) NOT NULL,
 ssn         varchar(11) NOT NULL,
 phone       varchar(10),
 birthday    date,
 salary      money,
 email       varchar(100)
);
 
-- Insert some data
INSERT INTO employees (name, ssn, phone, birthday, salary, email)
VALUES
( 'Freddie Mercury', '020-78-9345', '5081234567', '1946-09-05', 100000000.00, 'freddie.mercury@queen.com'),
( 'Brian May', '123-33-9345', '6171234567', '1947-07-19', 90000000.00, 'brian.may@queen.com'),
( 'Roger Taylor', '123-33-9345', '6171234567', '1949-07-26', 90000000.00, 'roger.taylor@queen.com'),
( 'John Deacon', '123-89-9345', '9781234567','1951-08-19', 50000000, 'john.deacon@queen.com');

CREATE OR REPLACE PROCEDURE list_employees
IS                                  
     v_id           NUMBER(4);      
     v_name         VARCHAR2(50);   
     CURSOR emp_cur IS               
         SELECT id, name FROM employees ORDER BY id;
BEGIN                                               
     OPEN emp_cur;                                   
     DBMS_OUTPUT.PUT_LINE('ID    NAME');         
     DBMS_OUTPUT.PUT_LINE('----  --------------------');       
     LOOP                                            
         FETCH emp_cur INTO v_id, v_name;        
         EXIT WHEN emp_cur%NOTFOUND;                 
         DBMS_OUTPUT.PUT_LINE(v_id || '     ' || v_name);
     END LOOP;                                               
     CLOSE emp_cur;                                          
END;                                                        
/

exec list_employees;
